### ISSUE TITLE
authenticating_with_oauth? causes trouble when dealing with users outside of requests

### ISSUE THREAD

**Issue by agibralter** [jrallison/authlogic_oauth#11]
I need to be able to interact with my User class outside of the Rails request (e.g. in script/console or in rake tasks). When I try to save my user `authenticating_with_oauth?` causes an exception because `session_class.controller` is nil (authlogic is not activated). Perhaps `authenticating_with_oauth?` could be wrapped with `if session_class.controller`?

<pre>
def authenticating_with_oauth?
  if session_class.controller
    # Initial request when user presses one of the button helpers
    (session_class.controller.params && !session_class.controller.params[:register_with_oauth].blank?) ||
    # When the oauth provider responds and we made the initial request
    (oauth_response && session_class.controller.session && session_class.controller.session[:oauth_request_class] == self.class.name)
  else
    false
  end
end
</pre>

**Comment by ess** [comment]
@agibralter -

You might want to take a look at, and add a vote for http://github.com/jrallison/authlogic_oauth/issues#issue/2 , as it is the same issue that you've noted.  As it were, it also includes a monkeypatch that you can dump in #{RAILS_ROOT}/lib and then load either in your console or your environment.rb

Granted, it appears that this issue has been fixed in a recent commit.  If you're still having trouble, you might try grabbing the latest-n-greatest.

**Comment by agibralter** [comment]
Ah cool, thank you! I'll close this ticket now.
